routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });


use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ContentController;

// Route::get('/index', function () {
//     return view('home.app');
// });

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/', 'HomeController@index');
Route::resource('content', 'ContentController');
Route::resource('user', 'UserController');
Route::resource('categori', 'CategoriController');
Route::resource('project', 'ProjectController');

app/Project.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
    protected $table = "portofolios";
    protected $guarded = [];

    public function users(){
        return $this->belongsTo('App\Users', 'portofolios_id', 'id');
    }
}

app/Http/Controllers/ProjectController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Project;
use Auth;
use PDF;

class ProjectController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $project = Project::all();
        // return $project;
        return view('project.index', compact('project'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('project.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'nama_project' => 'required',
            'foto' => 'required|image|mimes:jpeg,png,jpg|max:2048'

        ]);

        // menyimpan data file yang diupload ke variabel $file
        $file = $request->file('foto');

        $nama_file = time() . "_" . $file->getClientOriginalName();

        // isi dengan nama folder tempat kemana file diupload
        $tujuan_upload = "data_file";
        $file->move($tujuan_upload, $nama_file);

        Project::create([
            'nama_project' => $request->nama_project,
            'foto' => $nama_file,
            'portofolios_id' => Auth::id()
        ]);

        return redirect('/project')->with('success', 'Portofolio Berhasil Di Simpan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $project = Project::find($id);

        return view('project.show', compact('project'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Project::destroy($id);
        return redirect('/project')->with('success', 'Project Berhasil Di Hapus');
    }

    // public function cetak_pdf()
    // {
    //     $project = Project::all();

    //     $pdf = PDF::loadview('portofolio.project_pdf', compact('project'));
    //     return $pdf->download('laporan-project-' . date('Y-m-d_H-i-s') . '.pdf');
    // }
}

resources/views/project/create.blade.php
@extends('layouts.app')

@section('content')
<div class="ml-3 mt-3">
  <div class="card card-primary">
    <div class="card-header">
      <h3 class="card-title">Create Portofolio</h3>
    </div>
    <!-- /.card-header -->
    <!-- form start -->
    <form role="form" action="{{ route('project.store') }}" method="POST" enctype="multipart/form-data">
      @csrf
      <div class="card-body">
        <div class="form-group">
          <label for="title">Nama Portofolio</label>
          <input type="text" class="form-control" id="nama_project" name="nama_project" value="{{ old('nama_project','') }}" placeholder="Nama Project">
        </div>
        <div class="form-group">
            <label for="foto">Cover</label>
              <input type="file" class="uploads form-control" style="margin-top: 20px;" name="foto">
          </div>
        </div>

        <button type="submit" class="btn btn-primary" id="submit">
          Submit
        </button>
        <a href="/" class="btn btn-light pull-right">Back</a>
      </div>
  </div>
</form>
</div>
</div>
@endsection

resources/views/project/index.blade.php
@extends('layouts.app')

@section('content')
<div class="mt-3 ml-3 mr-3">
    <div class="card">
        <div class="card-header">
          <h3 class="card-title">Data Project</h3>
        </div>
        <!-- /.card-header -->
        <div class="card-body">
            @if (session('success'))
                <div class="alert alert-success">
                    {{session('success')}}
                </div>
            @endif
            <a class="btn btn-danger mb-3" href="{{route('project.create')}}">Tambah Project</a>
          <table class="table table-bordered">
            <thead>                  
              <tr>
                <th style="width: 10px">#</th>
                <th>Nama Project</th>
                <th>Image</th>
                <th>Nama Pembuat</th>
                <th style="width: 40px">Actions</th>
              </tr>
            </thead>
            <tbody>
                @foreach($project as $key => $post)
                <tr>
                    <td> {{ $key + 1 }} </td>
                    <td>{{$post->nama_project}}</td>
                    <td><img width="150px" src="{{ url('/data_file/'.$post->foto) }}"></td>
                    <td>{{$post->users->name}}</td>
                    <td style="display: flex;">
                        <a href="{{route('project.show', ['project' => $post->id])}}" class="btn btn-info btn-sm mr-1">
                            <i class="fa fa-eye"></i>
                        </a>
                        <form action="/project/{{$post->id}}" method="POST">
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="btn btn-danger btn-sm">
                                <i class="fa fa-trash"></i> 
                            </button>
                        </form>
                    </td>
                    
                </tr>
                @endforeach
            </tbody>
          </table>
        </div>
      </div>
</div>
@endsection

resources/views/project/show.blade.php
@extends('layouts.app')

@section('content')
<div class="ml-3 mt-3 mr-3">
    <div class="card card-danger">
        <div class="card-header">
        <h3 class="card-title">Lihat Project Id Ke {{$project->id}}</h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
    <form role="form" action="{{url('/project')}}" >
            @csrf <!--Token-->
        <div class="card-body">
            <div class="form-group">
            <label for="nama_project">Nama Project</label>
            <input type="nama_project" class="form-control" id="nama_project" name="nama_project" value="{{ old('nama_project', $project->nama_project) }}" readonly>
            @error('nama_project')
            <div class="alert alert-danger">{{ $message }}</div>
            @enderror
            </div>
            <div class="form-group">
                <label for="foto">Foto</label>
                <div>
                    
                <img width="500" height="500" src="{{ url('/data_file/'.$project->foto) }}"/>
                </div>
                @error('foto')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>
        </div>
        <!-- /.card-body -->

        <div class="card-footer">
            <button type="submit" class="btn btn-danger">Kembali</button>
        </div>
        </form>
    </div>    
</div>
    
@endsection