routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });


use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ContentController;

// Route::get('/index', function () {
//     return view('home.app');
// });

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/', 'HomeController@index');
Route::resource('content', 'ContentController');
Route::resource('user', 'UserController');
Route::resource('categori', 'CategoriController');
Route::resource('project', 'ProjectController');

app/Content.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Content extends Model
{
    protected $table = "contents";
    protected $guarded = [];
    
    public function kategori(){
        return $this->belongsTo('App\Categories', 'categories_id', 'id');
    }

    public function users(){
        return $this->belongsTo('App\Users', 'users_id', 'id');
    }
}

app/Http/Controllers/ContentController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use DB;
use Auth;
use App\Content;
use App\Categories;

class ContentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $content = Content::all();
        // return $content;
        return view('content.index', compact('content'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Categories::all();
        // return $categories;
        return view('content.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // $this->validate($request, [
        //     'categories_id' => 'required',
        //     'image' => 'required|image|mimes:jpeg,png,jpg|max:2048'
        // ]);

        $file = $request->file('image');
        $nama_file = time()."_".$file->getClientOriginalName();
          // isi dengan nama folder tempat kemana file diupload
        $tujuan_upload = "data_file_content";
        $file->move($tujuan_upload,$nama_file);
        
        Content::create([
            'judul'         => $request->judul,
            'isi'           => $request->isi,
            'image'         => $nama_file,
            'categories_id' => $request->categories_id,
            'users_id'      => Auth::id()
        ]);
            // return $content;
        return redirect('/content')->with('success', 'Content Berhasil Ditambahkan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $content = Content::find($id);

        return view('content.show', compact('content'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $content = Content::find($id);
        $categories = Categories::all();
        return view('content.edit', compact('content', 'categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {   
        // $file = $request->file('image');
        // if($file != ''  && $file != null){
        //     $file_old = $tujuan_upload.$file;
        //     unlink($file_old);
        // }
        
        // $nama_file = time()."_".$file->getClientOriginalName();
        // $tujuan_upload = "data_file_content";
        // $file->move($tujuan_upload,$nama_file);


        // $content = Content::find($id);

        // if($request->file('image') != ''){        
        //     $tujuan_upload = "data_file_content";
   
        //      //code for remove old file

   
        //      //upload new file
        //      $file = $request->file('image');
        //      $filename = time()."_".$file->getClientOriginalName();
        //      $file->move($tujuan_upload, $filename);
   
        //      //for update in table
        //     // $employee->update(['file' => $filename]);
        
        
        $update = Content::where('id', $id)->update([
            "judul"         => $request["judul"],
            "isi"           => $request["isi"],
            //"image"         => $nama_file,
            "categories_id" => $request["categories_id"],
            "users_id"      => Auth::id()
        ]);
        return redirect('/content')->with('success', 'Content Berhasil Di Update');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Content::destroy($id);
        return redirect('/content')->with('success', 'Content Berhasil Di Hapus');
    }
}

resources/views/content/create.blade.php
@extends('layouts.app')

@section('content')
<div class="ml-3 mt-3">
  <div class="card card-primary">
    <div class="card-header">
      <h3 class="card-title">Create Content</h3>
    </div>
    <!-- /.card-header -->
    <!-- form start -->
    <form role="form" action="{{ route('content.store') }}" method="POST" enctype="multipart/form-data">
      @csrf
      <div class="card-body">
        <div class="form-group">
          <label for="title">Judul</label>
          <input type="text" class="form-control" id="judul" name="judul" value="{{ old('judul','') }}" placeholder="Judul">
          @error('judul')
          <div class="alert alert-danger">{{ $message }}</div>
          @enderror
        </div>
        <div class="form-group">
          <label>Isi Description</label>
          <textarea class="form-control" rows="15" id="isi" name="isi" value="{{ old('isi','') }}" placeholder="Description ..."></textarea>
          @error('judul')
          <div class="alert alert-danger">{{ $message }}</div>
          @enderror
        </div>
        <div class="form-group">
          <label>Category</label>
          <select class="form-control" name="categories_id">
            <option value="">-pilih kategori-</option>
            @foreach ($categories as $item)
          <option value="{{$item->id}}" {{old('categories_id') == $item->id ? 'selected' : null}}>{{$item->nama_kategori}}</option>   
            @endforeach
          </select>
        </div>
        <div class="form-group">
          <label for="image" class="control-label">Cover</label>
            <input type="file" class="uploads form-control" style="margin-top: 20px;" name="image">
        </div>
      </div>
      <button type="submit" class="btn btn-primary" id="submit">Submit</button>
      <a href="/content" class="btn btn-light pull-right">Back</a>

</form>
</div>
</div>
@endsection

resources/views/content/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="ml-3 mt-3 mr-3">
    <div class="card card-danger">
        <div class="card-header">
        <h3 class="card-title">Edit Content Id Ke {{$content->id}}</h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
    <form role="form" action="/content/{{$content->id}}" method="POST">
        @csrf <!--Token-->
        @method('PUT')
        <div class="card-body">
            <div class="form-group">
            <label for="judl">Nama Project</label>
            <input type="judul" class="form-control" id="judul" name="judul" value="{{ old('judul', $content->judul) }}">
            @error('judul')
            <div class="alert alert-danger">{{ $message }}</div>
            @enderror
            </div>
            <div class="form-group">
                <label>Isi Description</label>
                <textarea class="form-control" rows="15" id="isi" name="isi" value="">{{ old('isi', $content->isi)}}</textarea>
                @error('isi')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror
              </div>
              <div class="form-group">
                <label>Category</label>
                <select class="form-control" name="categories_id">
                  @foreach ($categories as $item)
                <option value="{{$item->id}}" {{old('categories_id') == $item->id ? 'selected' : null}}>{{$item->nama_kategori}}</option>   
                  @endforeach
                </select>
              </div>
            <div class="form-group">
                <label for="foto">Foto</label>
                <div>
                    
                <img width="500" height="500" src="{{ url('/data_file_content/'.$content->image) }}"/>
                <input type="file" class="uploads form-control" style="margin-top: 20px;" name="image">    
            </div>
                @error('image')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>
        </div>
        <!-- /.card-body -->

        <div class="card-footer">
            <button type="submit" class="btn btn-danger">Edit</button>
            <button type="submit" class="btn btn-danger">Kembali</button>
        </div>
        </form>
    </div>    
</div>
    
@endsection

resources/views/content/index.blade.php
@extends('layouts.app')

@section('content')
<div class="row">

    <div class="col-lg-2">
        <a href="{{ url('content/create') }}" class="btn btn-primary btn-rounded btn-fw"><i class="fa fa-plus"></i> Tambah Content</a>
    </div>
    <div class="col-lg-12">
        @if (Session::has('message'))
        <div class="alert alert-{{ Session::get('message_type') }}" id="waktu2" style="margin-top:10px;">{{ Session::get('message') }}</div>
        @endif
    </div>
</div>
<div class="row" style="margin-top: 20px;">
    <div class="col-lg-12 grid-margin stretch-card">
        <div class="card">

            <div class="card-body">
                <h4 class="card-title">Data Content</h4>

                <div class="table-responsive">
                    <table class="table table-striped" id="table">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Image</th>
                                <th>Judul</th>
                                <th>Isi</th>
                                <th>Category</th>
                                <th>User</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                        @foreach($content as $key => $post)
                            <tr>
                                <td> {{ $key + 1 }} </td>
                                <td><img width="150px" src="{{ url('/data_file_content/'.$post->image) }}"></td>
                                <td>{{$post->judul}}</td>
                                <td>{{$post->isi}}</td>
                                <td>{{$post->kategori}}</td>
                                <td>{{$post->users->name}}</td>
                                <td style="display: flex;">
                                    <a href="{{route('content.show', ['content' => $post->id])}}" class="btn btn-info btn-sm mr-1">
                                        <i class="fa fa-eye"></i>
                                    </a>
                                    <a href="{{route('content.edit', ['content' => $post->id])}}" class="btn btn-secondary btn-sm mr-1">
                                        <i class="fa fa-edit"></i>
                                    </a>
                                    <form action="/content/{{$post->id}}" method="POST">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn btn-danger btn-sm">
                                            <i class="fa fa-trash"></i> 
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>

            </div>
        </div>
    </div>
</div>
@endsection

resources/views/content/show.blade.php
@extends('layouts.app')

@section('content')
<div class="ml-3 mt-3 mr-3">
    <div class="card card-danger">
        <div class="card-header">
        <h3 class="card-title">Lihat Project Id Ke {{$content->id}}</h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
    <form role="form" action="{{url('/content')}}" >
            @csrf <!--Token-->
        <div class="card-body">
            <div class="form-group">
            <label for="judl">Nama Project</label>
            <input type="judul" class="form-control" id="judul" name="judul" value="{{ old('judul', $content->judul) }}" readonly>
            @error('judul')
            <div class="alert alert-danger">{{ $message }}</div>
            @enderror
            </div>
            <div class="form-group">
                <label>Isi Description</label>
                <textarea class="form-control" rows="15" id="isi" name="isi" value="" readonly>{{ old('isi', $content->isi)}}</textarea>
                @error('isi')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror
              </div>
              <div class="form-group">
                <label for="categories_id">Nama Kategori</label>
                <input type="categories_id" class="form-control" id="categories_id" name="categories_id" value="{{ old('judul', $content->kategori->nama_kategori) }}" readonly>
                @error('categories_id')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror
                </div>
            <div class="form-group">
                <label for="foto">Foto</label>
                <div>
                    
                <img width="500" height="500" src="{{ url('/data_file_content/'.$content->image) }}"/>
                </div>
                @error('foto')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>
        </div>
        <!-- /.card-body -->

        <div class="card-footer">
            <button type="submit" class="btn btn-danger">Kembali</button>
        </div>
        </form>
    </div>    
</div>
    
@endsection