routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });


use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ContentController;

// Route::get('/index', function () {
//     return view('home.app');
// });

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/', 'HomeController@index');
Route::resource('content', 'ContentController');
Route::resource('user', 'UserController');
Route::resource('categori', 'CategoriController');
Route::resource('project', 'ProjectController');

resources/views/categories/create.blade.php
@extends('layouts.app')

@section('content')
<div class="ml-3 mt-3">
  <div class="card card-primary">
    <div class="card-header">
      <h3 class="card-title">Create Categories</h3>
    </div>
    <!-- /.card-header -->
    <!-- form start -->
    <form role="form" action="{{ route('categori.store') }}" method="POST" enctype="multipart/form-data">
      @csrf
      <div class="card-body">
        <div class="form-group">
          <label for="title">Nama Kategori</label>
          <input type="text" class="form-control" id="nama_kategori" name="nama_kategori" value="{{ old('nama_kategori','') }}" placeholder="Nama Categori">
          @error('nama_kategori')
          <div class="alert alert-danger">{{ $message }}</div>
          @enderror
        </div>
        <button type="submit" class="btn btn-primary" id="submit">
          Submit
        </button>
        <a href="/" class="btn btn-light pull-right">Back</a>

      </div>
  </div>
</div>

</form>
</div>
</div>
@endsection

resources/views/categories/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="ml-3 mt-3 mr-3">
    <div class="card card-danger">
        <div class="card-header">
        <h3 class="card-title">Edit Pertanyaan Id Ke {{$kategori->id}}</h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
        <form role="form" action="/categori/{{$kategori->id}}" method="POST">
            @csrf <!--Token-->
            @method('PUT')
            <div class="card-body">
                <div class="form-group">
                <label for="nama_kategori">Nama kategori</label>
                <input type="nama_kategori" class="form-control" id="nama_kategori" name="nama_kategori" value="{{ old('nama_kategori', $kategori->nama_kategori) }}">
                @error('nama_kategori')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror
                </div>
            </div>
        <!-- /.card-body -->

        <div class="card-footer">
            <button type="submit" class="btn btn-danger">Edit</button>
            <a href="/categori" class="btn btn-secondary">Kembali</a>
        </div>
        </form>
    </div>    
</div>

@endsection

resources/views/categories/index.blade.php
@extends('layouts.app')

@section('content')
<div class="mt-3 ml-3 mr-3">
    <div class="card">
        <div class="card-header">
          <h3 class="card-title">Data Categories</h3>
        </div>
        <!-- /.card-header -->
        <div class="card-body">
            @if (session('success'))
                <div class="alert alert-success">
                    {{session('success')}}
                </div>
            @endif
            <a class="btn btn-danger mb-3" href="{{route('categori.create')}}">Tambah Categories</a>
          <table class="table table-bordered">
            <thead>                  
              <tr>
                <th style="width: 10px">#</th>
                <th>Nama Cotegories</th>
                <th style="width: 40px">Actions</th>
              </tr>
            </thead>
            <tbody>
                <!--looping untuk mengambil data-->
               @forelse ($kategori as $key => $post)
                    <tr>
                        <td> {{ $key + 1 }} </td>
                        <td> {{ $post->nama_kategori }} </td>
                        <td style="display: flex;">
                            <a href="{{route('categori.show', ['categori' => $post->id])}}" class="btn btn-info btn-sm mr-1">
                                <i class="fa fa-eye"></i>
                            </a>
                            <a href="{{route('categori.edit', ['categori' => $post->id])}}" class="btn btn-secondary btn-sm mr-1">
                                <i class="fa fa-edit"></i>
                            </a>
                            <form action="/categori/{{$post->id}}" method="POST">
                                @csrf
                                @method('DELETE')
                                <button type="submit" class="btn btn-danger btn-sm">
                                    <i class="fa fa-trash"></i> 
                                </button>
                            </form>
                        </td>
                    </tr>
                    @empty
                    <tr>
                        <td colspan="4" align="center">Data Kosong</td>    
                    </tr>
                @endforelse                
            </tbody>
          </table>
        </div>
        <!-- /.card-body -->
        <!--paginantion            
        <div class="card-footer clearfix">
        <ul class="pagination pagination-sm m-0 float-right">
            <li class="page-item"><a class="page-link" href="#">«</a></li>
            <li class="page-item"><a class="page-link" href="#">1</a></li>
            <li class="page-item"><a class="page-link" href="#">2</a></li>
            <li class="page-item"><a class="page-link" href="#">3</a></li>
            <li class="page-item"><a class="page-link" href="#">»</a></li>
          </ul>
        </div>-->

      </div>
</div>
@endsection

{{-- @push('script')
<script type="text/javascript">
    $(document).ready(function() {
        $('#table').DataTable({
            "iDisplayLength": 50
        });

    });
</script>
@endpush --}}

resources/views/categories/show.blade.php
@extends('layouts.app')

@section('content')
<div class="ml-3 mt-3 mr-3">
    <div class="card card-danger">
        <div class="card-header">
        <h3 class="card-title">Lihat Categories Id Ke {{$kategori->id}}</h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
    <form role="form" action="{{url('/categori')}}" >
            @csrf <!--Token-->
        <div class="card-body">
            <div class="form-group">
            <label for="nama_kategori">Nama kategori</label>
            <input type="nama_kategori" class="form-control" id="nama_kategori" name="nama_kategori" value="{{ old('nama_kategori', $kategori->nama_kategori) }}" readonly>
            @error('nama_kategori')
            <div class="alert alert-danger">{{ $message }}</div>
            @enderror
            </div>
        </div>
        <!-- /.card-body -->

        <div class="card-footer">
            <button type="submit" class="btn btn-danger">Kembali</button>
        </div>
        </form>
    </div>    
</div>
    
@endsection